[build]
builder = "nixpacks"

[deploy]
startCommand = "python bot.py"

[variables]
API_TOKEN = "8568019720:AAGZhJHAvxNl2_CVYFgzW6B7nTKXZBDuUs8"
MAIN_ADMIN_ID = "8358009538"
SECRET_KEY = "ваш_секретный_ключ_32_символа"
ENCRYPTION_KEY = "ваш_ключ_шифрования_32_символа"